/** Biblioteca inicial de stamps para la pizarra (cast: Excalidraw exige campos internos). */
export const STUDY_LIBRARY_ITEMS = [
  {
    id: 'right_triangle',
    status: 'published',
    created: 1,
    name: 'Triángulo rectángulo',
    elements: [
      {
        type: 'line',
        version: 1,
        versionNonce: 1,
        isDeleted: false,
        id: 'stamp-rt',
        fillStyle: 'solid',
        strokeWidth: 2,
        strokeStyle: 'solid',
        roughness: 1,
        opacity: 100,
        angle: 0,
        x: 0,
        y: 0,
        strokeColor: '#2563eb',
        backgroundColor: 'transparent',
        width: 140,
        height: 100,
        seed: 1,
        groupIds: [],
        frameId: null,
        roundness: null,
        boundElements: null,
        updated: 1,
        link: null,
        locked: false,
        index: 'a0',
        points: [
          [0, 100],
          [140, 100],
          [0, 0],
          [0, 100],
        ],
        lastCommittedPoint: null,
        startBinding: null,
        endBinding: null,
        startArrowhead: null,
        endArrowhead: null,
      },
    ],
  },
  {
    id: 'circle',
    status: 'published',
    created: 1,
    name: 'Círculo',
    elements: [
      {
        type: 'ellipse',
        version: 1,
        versionNonce: 2,
        isDeleted: false,
        id: 'stamp-circle',
        fillStyle: 'solid',
        strokeWidth: 2,
        strokeStyle: 'solid',
        roughness: 1,
        opacity: 100,
        angle: 0,
        x: 0,
        y: 0,
        strokeColor: '#2563eb',
        backgroundColor: 'transparent',
        width: 100,
        height: 100,
        seed: 2,
        groupIds: [],
        frameId: null,
        roundness: null,
        boundElements: null,
        updated: 1,
        link: null,
        locked: false,
        index: 'a1',
      },
    ],
  },
  {
    id: 'square',
    status: 'published',
    created: 1,
    name: 'Cuadrado',
    elements: [
      {
        type: 'rectangle',
        version: 1,
        versionNonce: 3,
        isDeleted: false,
        id: 'stamp-square',
        fillStyle: 'solid',
        strokeWidth: 2,
        strokeStyle: 'solid',
        roughness: 1,
        opacity: 100,
        angle: 0,
        x: 0,
        y: 0,
        strokeColor: '#2563eb',
        backgroundColor: 'transparent',
        width: 100,
        height: 100,
        seed: 3,
        groupIds: [],
        frameId: null,
        roundness: { type: 3 },
        boundElements: null,
        updated: 1,
        link: null,
        locked: false,
        index: 'a2',
      },
    ],
  },
  {
    id: 'arrow',
    status: 'published',
    created: 1,
    name: 'Flecha',
    elements: [
      {
        type: 'arrow',
        version: 1,
        versionNonce: 4,
        isDeleted: false,
        id: 'stamp-arrow',
        fillStyle: 'solid',
        strokeWidth: 2,
        strokeStyle: 'solid',
        roughness: 1,
        opacity: 100,
        angle: 0,
        x: 0,
        y: 0,
        strokeColor: '#2563eb',
        backgroundColor: 'transparent',
        width: 140,
        height: 0,
        seed: 4,
        groupIds: [],
        frameId: null,
        roundness: null,
        boundElements: null,
        updated: 1,
        link: null,
        locked: false,
        index: 'a3',
        points: [
          [0, 0],
          [140, 0],
        ],
        lastCommittedPoint: null,
        startBinding: null,
        endBinding: null,
        startArrowhead: null,
        endArrowhead: 'arrow',
      },
    ],
  },
] as const
